<?php

function profile_theme($existing, $type, $theme, $path) {
  $module_path = \Drupal::service('extension.list.module')->getPath('profile') . '/templates';

  return [
    'family_members_block' => [
      'variables' => ['members' => []],
      'template' => 'family-members-block',
      'path' => $module_path,
    ],
    'profile' => [
      'variables' => [
        'form' => NULL,
        'profile_picture_form' => NULL,
        'family_form' => NULL,
        'my_profile_title' => NULL,
      ],
      'template' => 'profile',
      'path' => $module_path,
    ],
    'add-family-member' => [
      'render element' => 'form',
      'template' => 'add-family-member',
      'path' => \Drupal::service('extension.list.module')->getPath('profile') . '/templates',
    ],
    'success-family-member' => [
      'render element' => 'elements',
      'template' => 'success-family-member', // Refers to my-static-page.html.twig
    ],
    'change-password' => [
      'render element' => 'form',
      'template' => 'change-password',
      'path' => \Drupal::service('extension.list.module')->getPath('profile') . '/templates',
    ]
  ];
}


function profile_preprocess_page(array &$variables)
{
    if (\Drupal::routeMatch()->getRouteName() === 'profile.my_account') {

        // Optional: load custom block body field
        $block_storage = \Drupal::entityTypeManager()->getStorage('block_content');
        $blocks = $block_storage->loadByProperties([
            'type' => 'basic',
            'status' => 1,
        ]);
        $block = reset($blocks);
        if ($block && $block->hasField('body')) {
            $variables['my_profile_title'] = $block->get('body')->value;
        }
    }
}

